### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by kevin-Curry** [baumph/Surface-Book-1-Hackintosh#2]
I don't know why but it's not working at all.
I didn't even see open core
only a code which told me that config.plist has some problems

**Comment by baumph** [comment]
What OS Version are you trying to install? 
And please make sure, that you have the same hardware that my Surface has. 

Can you boot to OC at all, or does it fail after selecting the USB? And what does the Error-Code say?

**Comment by kevin-Curry** [comment]
I'm sure the hardware is the same.
I was trying to install big sur 11.2.3.
The Code was 'OC: Driver OpenRuntine.efu at 0 cannot be loaded - Access Denied'

**Comment by baumph** [comment]
Big Sur with the same hardware should work. Let me just irritate, you can’t see an OC boot picker, right? When that’s the case you probably have to change some setting in the Surface Bios
